apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: teste-secret-env
  name: teste-secret-env
spec:
  containers:
  - image: busybox
    name: teste-secret-env
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
