apiVersion: batch/v1
kind: CronJob
metadata:
  name: giropops-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: giropops
            image: busybox
            args:
            - /bin/sh
            - -c
            - data; echo Bem vindo ao Descomplicando Kubernetes - LinuxTips VAIIII ; sleep 30
          restartPolicy: OnFailure
