---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mydb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
