apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox-liv-read
  name: busybox-liv-read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-liv-read
  template:
    metadata:
      labels:
        app: busybox-liv-read
    spec:
      containers:
      - image: busybox
        name: busybox
        resources:
          limits:
            cpu: "250m"
            memory: "512Mi"
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
