apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-secret-filesystem
  name: nginx-secret-filesystem
spec:
  containers:
  - image: nginx
    name: nginx-secret-filesystem
    volumeMounts:
    - name: secret
      mountPath: "/giropops"
      readOnly: false
  volumes:
  - name: secret
    secret:
      secretName: secret
      items:
      - key: pass
        path: mysecret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
