apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-secret-env
  name: nginx-secret-env
spec:
  containers:
  - image: nginx
    name: nginx-secret-env
    env:
      - name: giropops
        valueFrom:
          secretKeyRef:
            name: secret-env
            key: giropops
