apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-limit
  name: nginx-limit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-limit
  template:
    metadata:
      labels:
        app: nginx-limit
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: "250m"
            memory: "512Mi"
