---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: containers
  name: containers
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  - image: busybox
    name: busybox1
    command: ["sh", "-c", "while true; do uname -a >> /tmp/index.html; date >> /tmp/index.html; sleep 2; done"]
    volumeMounts:
     - name: workdir
       mountPath: /tmp/
  - image: busybox
    name: busybox2
    command: ["sh", "-c", "tail -f /tmp/index.html"]
    volumeMounts:
    - name: workdir
      mountPath: /tmp
  volumes:
  - name: workdir
    emptyDir: {}
  dnsPolicy: ClusterFirst
