apiVersion: v2
name: giropops
description: Primeiro Chart
type: application
version: 0.2
appVersion: "1.0.0"
keywords:
  - nginx
  - primeira_aula
  - webserver
  - giropops
maintainers:
  - name: Hailson Junior
    email: hailson.fsj@gmail.com
deprecated: false    
